function [dense_1, state] = landmarkFcn(image_input, params, varargin)
%LANDMARKFCN Function implementing an imported ONNX network.
%
% THIS FILE WAS AUTO-GENERATED BY importONNXFunction.
% ONNX Operator Set Version: 15
%
% Variable names in this function are taken from the original ONNX file.
%
% [DENSE_1] = landmarkFcn(IMAGE_INPUT, PARAMS)
%			- Evaluates the imported ONNX network LANDMARKFCN with input(s)
%			IMAGE_INPUT and the imported network parameters in PARAMS. Returns
%			network output(s) in DENSE_1.
%
% [DENSE_1, STATE] = landmarkFcn(IMAGE_INPUT, PARAMS)
%			- Additionally returns state variables in STATE. When training,
%			use this form and set TRAINING to true.
%
% [__] = landmarkFcn(IMAGE_INPUT, PARAMS, 'NAME1', VAL1, 'NAME2', VAL2, ...)
%			- Specifies additional name-value pairs described below:
%
% 'Training'
% 			Boolean indicating whether the network is being evaluated for
%			prediction or training. If TRAINING is true, state variables
%			will be updated.
%
% 'InputDataPermutation'
%			'auto' - Automatically attempt to determine the permutation
%			 between the dimensions of the input data and the dimensions of
%			the ONNX model input. For example, the permutation from HWCN
%			(MATLAB standard) to NCHW (ONNX standard) uses the vector
%			[4 3 1 2]. See the documentation for IMPORTONNXFUNCTION for
%			more information about automatic permutation.
%
%			'none' - Input(s) are passed in the ONNX model format. See 'Inputs'.
%
%			numeric vector - The permutation vector describing the
%			transformation between input data dimensions and the expected
%			ONNX input dimensions.%
%			cell array - If the network has multiple inputs, each cell
%			contains 'auto', 'none', or a numeric vector.
%
% 'OutputDataPermutation'
%			'auto' - Automatically attempt to determine the permutation
%			between the dimensions of the output and a conventional MATLAB
%			dimension ordering. For example, the permutation from NC (ONNX
%			standard) to CN (MATLAB standard) uses the vector [2 1]. See
%			the documentation for IMPORTONNXFUNCTION for more information
%			about automatic permutation.
%
%			'none' - Return output(s) as given by the ONNX model. See 'Outputs'.
%
%			numeric vector - The permutation vector describing the
%			transformation between the ONNX output dimensions and the
%			desired output dimensions.%
%			cell array - If the network has multiple outputs, each cell
%			contains 'auto', 'none' or a numeric vector.
%
% Inputs:
% -------
% IMAGE_INPUT
%			- Input(s) to the ONNX network.
%			  The input size(s) expected by the ONNX file are:
%				  IMAGE_INPUT:		[unk__88, 128, 128, 3]				Type: FLOAT
%			  By default, the function will try to permute the input(s)
%			  into this dimension ordering. If the default is incorrect,
%			  use the 'InputDataPermutation' argument to control the
%			  permutation.
%
%
% PARAMS	- Network parameters returned by 'importONNXFunction'.
%
%
% Outputs:
% --------
% DENSE_1
%			- Output(s) of the ONNX network.
%			  Without permutation, the size(s) of the outputs are:
%				  DENSE_1:		[unk__89, 136]				Type: FLOAT
%			  By default, the function will try to permute the output(s)
%			  from this dimension ordering into a conventional MATLAB
%			  ordering. If the default is incorrect, use the
%			  'OutputDataPermutation' argument to control the permutation.
%
% STATE		- (Optional) State variables. When TRAINING is true, these will
% 			  have been updated from the original values in PARAMS.State.
%
%
%  See also importONNXFunction

% Preprocess the input data and arguments:
[image_input, Training, outputDataPerms, anyDlarrayInputs] = preprocessInput(image_input, params, varargin{:});
% Put all variables into a single struct to implement dynamic scoping:
[Vars, NumDims] = packageVariables(params, {'image_input'}, {image_input}, [4]);
% Call the top-level graph function:
[dense_1, dense_1NumDims, state] = tf2onnxGraph1000(image_input, NumDims.image_input, Vars, NumDims, Training, params.State);
% Postprocess the output data
[dense_1] = postprocessOutput(dense_1, outputDataPerms, anyDlarrayInputs, Training, varargin{:});
end

function [dense_1, dense_1NumDims1040, state] = tf2onnxGraph1000(image_input, image_inputNumDims1039, Vars, NumDims, Training, state)
% Function implementing the graph 'tf2onnxGraph1000'
% Update Vars and NumDims from the graph's formal input parameters. Note that state variables are already in Vars.
Vars.image_input = image_input;
NumDims.image_input = image_inputNumDims1039;

% Execute the operators:
% Sub:
Vars.StatefulPartitionedCall_landmark_norma_2 = Vars.image_input - Vars.StatefulPartitionedCall_landmark_normali;
NumDims.StatefulPartitionedCall_landmark_norma_2 = max(NumDims.image_input, NumDims.StatefulPartitionedCall_landmark_normali);

% Mul:
Vars.StatefulPartitionedCall_landmark_norma_4 = Vars.StatefulPartitionedCall_landmark_norma_2 .* Vars.ConstantFolding_StatefulPartitionedCall_;
NumDims.StatefulPartitionedCall_landmark_norma_4 = max(NumDims.StatefulPartitionedCall_landmark_norma_2, NumDims.ConstantFolding_StatefulPartitionedCall_);

% Transpose:
[perm, NumDims.StatefulPartitionedCall_landmark_conv2_4] = prepareTransposeArgs(Vars.TransposePerm1001, NumDims.StatefulPartitionedCall_landmark_norma_4);
if isempty(perm)
    Vars.StatefulPartitionedCall_landmark_conv2_4 = Vars.StatefulPartitionedCall_landmark_norma_4;
else
    Vars.StatefulPartitionedCall_landmark_conv2_4 = permute(Vars.StatefulPartitionedCall_landmark_norma_4, perm);
end

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.StatefulPartitionedCall_landmark_conv2_2] = prepareConvArgs(Vars.StatefulPartitionedCall_landmark_conv2_5, Vars.StatefulPartitionedCall_landmark_conv2_1, Vars.ConvStride1002, Vars.ConvDilationFactor1003,Vars.ConvPadding1004, 1, NumDims.StatefulPartitionedCall_landmark_conv2_4, NumDims.StatefulPartitionedCall_landmark_conv2_5);
Vars.StatefulPartitionedCall_landmark_conv2_2 = dlconv(Vars.StatefulPartitionedCall_landmark_conv2_4, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.StatefulPartitionedCall_landmark_conv2_7 = relu(dlarray(Vars.StatefulPartitionedCall_landmark_conv2_2));
NumDims.StatefulPartitionedCall_landmark_conv2_7 = NumDims.StatefulPartitionedCall_landmark_conv2_2;

% BatchNormalization:
[offset, scale, datasetMean, datasetVariance, dataFormat, NumDims.StatefulPartitionedCall_landmark_batch_3, NumDims.StatefulPartitionedCall_landmark_batch_1, NumDims.StatefulPartitionedCall_landmark_batch_2] = prepareBatchNormalizationArgs(Vars.StatefulPartitionedCall_landmark_batch_5, Vars.StatefulPartitionedCall_landmark_batch_4, Vars.StatefulPartitionedCall_landmark_batch_1, Vars.StatefulPartitionedCall_landmark_batch_2, NumDims.StatefulPartitionedCall_landmark_conv2_7, NumDims.StatefulPartitionedCall_landmark_batch_1, NumDims.StatefulPartitionedCall_landmark_batch_2);
if Training
    [Vars.StatefulPartitionedCall_landmark_batch_3, dsmean, dsvar] = batchnorm(Vars.StatefulPartitionedCall_landmark_conv2_7, offset, scale, datasetMean, datasetVariance, 'Epsilon', 0.001000, 'DataFormat', dataFormat);
    Vars.StatefulPartitionedCall_landmark_batch_1 = dlarray(dsmean);
    Vars.StatefulPartitionedCall_landmark_batch_2 = dlarray(dsvar);
else
    Vars.StatefulPartitionedCall_landmark_batch_3 = batchnorm(Vars.StatefulPartitionedCall_landmark_conv2_7, offset, scale, datasetMean, datasetVariance, 'Epsilon', 0.001000, 'DataFormat', dataFormat);
end

% MaxPool:
[poolsize, stride, padding, dataFormat, NumDims.StatefulPartitionedCall_landmark_max_p_1] = prepareMaxPool8Args(Vars.MaxPoolPoolSize1005, Vars.MaxPoolStride1006, Vars.MaxPoolPadding1007, NumDims.StatefulPartitionedCall_landmark_batch_3);
Vars.StatefulPartitionedCall_landmark_max_p_1 = maxpool(Vars.StatefulPartitionedCall_landmark_batch_3, poolsize, 'Stride', stride, 'Padding', padding, 'DataFormat', dataFormat);

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.StatefulPartitionedCall_landmark_conv_10] = prepareConvArgs(Vars.StatefulPartitionedCall_landmark_conv_11, Vars.StatefulPartitionedCall_landmark_conv2_9, Vars.ConvStride1008, Vars.ConvDilationFactor1009,Vars.ConvPadding1010, 1, NumDims.StatefulPartitionedCall_landmark_max_p_1, NumDims.StatefulPartitionedCall_landmark_conv_11);
Vars.StatefulPartitionedCall_landmark_conv_10 = dlconv(Vars.StatefulPartitionedCall_landmark_max_p_1, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.StatefulPartitionedCall_landmark_conv_13 = relu(dlarray(Vars.StatefulPartitionedCall_landmark_conv_10));
NumDims.StatefulPartitionedCall_landmark_conv_13 = NumDims.StatefulPartitionedCall_landmark_conv_10;

% BatchNormalization:
[offset, scale, datasetMean, datasetVariance, dataFormat, NumDims.StatefulPartitionedCall_landmark_batch_9, NumDims.StatefulPartitionedCall_landmark_batch_7, NumDims.StatefulPartitionedCall_landmark_batch_8] = prepareBatchNormalizationArgs(Vars.StatefulPartitionedCall_landmark_batc_11, Vars.StatefulPartitionedCall_landmark_batc_10, Vars.StatefulPartitionedCall_landmark_batch_7, Vars.StatefulPartitionedCall_landmark_batch_8, NumDims.StatefulPartitionedCall_landmark_conv_13, NumDims.StatefulPartitionedCall_landmark_batch_7, NumDims.StatefulPartitionedCall_landmark_batch_8);
if Training
    [Vars.StatefulPartitionedCall_landmark_batch_9, dsmean, dsvar] = batchnorm(Vars.StatefulPartitionedCall_landmark_conv_13, offset, scale, datasetMean, datasetVariance, 'Epsilon', 0.001000, 'DataFormat', dataFormat);
    Vars.StatefulPartitionedCall_landmark_batch_7 = dlarray(dsmean);
    Vars.StatefulPartitionedCall_landmark_batch_8 = dlarray(dsvar);
else
    Vars.StatefulPartitionedCall_landmark_batch_9 = batchnorm(Vars.StatefulPartitionedCall_landmark_conv_13, offset, scale, datasetMean, datasetVariance, 'Epsilon', 0.001000, 'DataFormat', dataFormat);
end

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.StatefulPartitionedCall_landmark_conv_16] = prepareConvArgs(Vars.StatefulPartitionedCall_landmark_conv_17, Vars.StatefulPartitionedCall_landmark_conv_15, Vars.ConvStride1011, Vars.ConvDilationFactor1012,Vars.ConvPadding1013, 1, NumDims.StatefulPartitionedCall_landmark_batch_9, NumDims.StatefulPartitionedCall_landmark_conv_17);
Vars.StatefulPartitionedCall_landmark_conv_16 = dlconv(Vars.StatefulPartitionedCall_landmark_batch_9, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.StatefulPartitionedCall_landmark_conv_19 = relu(dlarray(Vars.StatefulPartitionedCall_landmark_conv_16));
NumDims.StatefulPartitionedCall_landmark_conv_19 = NumDims.StatefulPartitionedCall_landmark_conv_16;

% BatchNormalization:
[offset, scale, datasetMean, datasetVariance, dataFormat, NumDims.StatefulPartitionedCall_landmark_batc_15, NumDims.StatefulPartitionedCall_landmark_batc_13, NumDims.StatefulPartitionedCall_landmark_batc_14] = prepareBatchNormalizationArgs(Vars.StatefulPartitionedCall_landmark_batc_17, Vars.StatefulPartitionedCall_landmark_batc_16, Vars.StatefulPartitionedCall_landmark_batc_13, Vars.StatefulPartitionedCall_landmark_batc_14, NumDims.StatefulPartitionedCall_landmark_conv_19, NumDims.StatefulPartitionedCall_landmark_batc_13, NumDims.StatefulPartitionedCall_landmark_batc_14);
if Training
    [Vars.StatefulPartitionedCall_landmark_batc_15, dsmean, dsvar] = batchnorm(Vars.StatefulPartitionedCall_landmark_conv_19, offset, scale, datasetMean, datasetVariance, 'Epsilon', 0.001000, 'DataFormat', dataFormat);
    Vars.StatefulPartitionedCall_landmark_batc_13 = dlarray(dsmean);
    Vars.StatefulPartitionedCall_landmark_batc_14 = dlarray(dsvar);
else
    Vars.StatefulPartitionedCall_landmark_batc_15 = batchnorm(Vars.StatefulPartitionedCall_landmark_conv_19, offset, scale, datasetMean, datasetVariance, 'Epsilon', 0.001000, 'DataFormat', dataFormat);
end

% MaxPool:
[poolsize, stride, padding, dataFormat, NumDims.StatefulPartitionedCall_landmark_max_p_3] = prepareMaxPool8Args(Vars.MaxPoolPoolSize1014, Vars.MaxPoolStride1015, Vars.MaxPoolPadding1016, NumDims.StatefulPartitionedCall_landmark_batc_15);
Vars.StatefulPartitionedCall_landmark_max_p_3 = maxpool(Vars.StatefulPartitionedCall_landmark_batc_15, poolsize, 'Stride', stride, 'Padding', padding, 'DataFormat', dataFormat);

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.StatefulPartitionedCall_landmark_conv_22] = prepareConvArgs(Vars.StatefulPartitionedCall_landmark_conv_23, Vars.StatefulPartitionedCall_landmark_conv_21, Vars.ConvStride1017, Vars.ConvDilationFactor1018,Vars.ConvPadding1019, 1, NumDims.StatefulPartitionedCall_landmark_max_p_3, NumDims.StatefulPartitionedCall_landmark_conv_23);
Vars.StatefulPartitionedCall_landmark_conv_22 = dlconv(Vars.StatefulPartitionedCall_landmark_max_p_3, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.StatefulPartitionedCall_landmark_conv_25 = relu(dlarray(Vars.StatefulPartitionedCall_landmark_conv_22));
NumDims.StatefulPartitionedCall_landmark_conv_25 = NumDims.StatefulPartitionedCall_landmark_conv_22;

% BatchNormalization:
[offset, scale, datasetMean, datasetVariance, dataFormat, NumDims.StatefulPartitionedCall_landmark_batc_21, NumDims.StatefulPartitionedCall_landmark_batc_19, NumDims.StatefulPartitionedCall_landmark_batc_20] = prepareBatchNormalizationArgs(Vars.StatefulPartitionedCall_landmark_batc_23, Vars.StatefulPartitionedCall_landmark_batc_22, Vars.StatefulPartitionedCall_landmark_batc_19, Vars.StatefulPartitionedCall_landmark_batc_20, NumDims.StatefulPartitionedCall_landmark_conv_25, NumDims.StatefulPartitionedCall_landmark_batc_19, NumDims.StatefulPartitionedCall_landmark_batc_20);
if Training
    [Vars.StatefulPartitionedCall_landmark_batc_21, dsmean, dsvar] = batchnorm(Vars.StatefulPartitionedCall_landmark_conv_25, offset, scale, datasetMean, datasetVariance, 'Epsilon', 0.001000, 'DataFormat', dataFormat);
    Vars.StatefulPartitionedCall_landmark_batc_19 = dlarray(dsmean);
    Vars.StatefulPartitionedCall_landmark_batc_20 = dlarray(dsvar);
else
    Vars.StatefulPartitionedCall_landmark_batc_21 = batchnorm(Vars.StatefulPartitionedCall_landmark_conv_25, offset, scale, datasetMean, datasetVariance, 'Epsilon', 0.001000, 'DataFormat', dataFormat);
end

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.StatefulPartitionedCall_landmark_conv_28] = prepareConvArgs(Vars.StatefulPartitionedCall_landmark_conv_29, Vars.StatefulPartitionedCall_landmark_conv_27, Vars.ConvStride1020, Vars.ConvDilationFactor1021,Vars.ConvPadding1022, 1, NumDims.StatefulPartitionedCall_landmark_batc_21, NumDims.StatefulPartitionedCall_landmark_conv_29);
Vars.StatefulPartitionedCall_landmark_conv_28 = dlconv(Vars.StatefulPartitionedCall_landmark_batc_21, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.StatefulPartitionedCall_landmark_conv_31 = relu(dlarray(Vars.StatefulPartitionedCall_landmark_conv_28));
NumDims.StatefulPartitionedCall_landmark_conv_31 = NumDims.StatefulPartitionedCall_landmark_conv_28;

% BatchNormalization:
[offset, scale, datasetMean, datasetVariance, dataFormat, NumDims.StatefulPartitionedCall_landmark_batc_27, NumDims.StatefulPartitionedCall_landmark_batc_25, NumDims.StatefulPartitionedCall_landmark_batc_26] = prepareBatchNormalizationArgs(Vars.StatefulPartitionedCall_landmark_batc_29, Vars.StatefulPartitionedCall_landmark_batc_28, Vars.StatefulPartitionedCall_landmark_batc_25, Vars.StatefulPartitionedCall_landmark_batc_26, NumDims.StatefulPartitionedCall_landmark_conv_31, NumDims.StatefulPartitionedCall_landmark_batc_25, NumDims.StatefulPartitionedCall_landmark_batc_26);
if Training
    [Vars.StatefulPartitionedCall_landmark_batc_27, dsmean, dsvar] = batchnorm(Vars.StatefulPartitionedCall_landmark_conv_31, offset, scale, datasetMean, datasetVariance, 'Epsilon', 0.001000, 'DataFormat', dataFormat);
    Vars.StatefulPartitionedCall_landmark_batc_25 = dlarray(dsmean);
    Vars.StatefulPartitionedCall_landmark_batc_26 = dlarray(dsvar);
else
    Vars.StatefulPartitionedCall_landmark_batc_27 = batchnorm(Vars.StatefulPartitionedCall_landmark_conv_31, offset, scale, datasetMean, datasetVariance, 'Epsilon', 0.001000, 'DataFormat', dataFormat);
end

% MaxPool:
[poolsize, stride, padding, dataFormat, NumDims.StatefulPartitionedCall_landmark_max_p_5] = prepareMaxPool8Args(Vars.MaxPoolPoolSize1023, Vars.MaxPoolStride1024, Vars.MaxPoolPadding1025, NumDims.StatefulPartitionedCall_landmark_batc_27);
Vars.StatefulPartitionedCall_landmark_max_p_5 = maxpool(Vars.StatefulPartitionedCall_landmark_batc_27, poolsize, 'Stride', stride, 'Padding', padding, 'DataFormat', dataFormat);

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.StatefulPartitionedCall_landmark_conv_34] = prepareConvArgs(Vars.StatefulPartitionedCall_landmark_conv_35, Vars.StatefulPartitionedCall_landmark_conv_33, Vars.ConvStride1026, Vars.ConvDilationFactor1027,Vars.ConvPadding1028, 1, NumDims.StatefulPartitionedCall_landmark_max_p_5, NumDims.StatefulPartitionedCall_landmark_conv_35);
Vars.StatefulPartitionedCall_landmark_conv_34 = dlconv(Vars.StatefulPartitionedCall_landmark_max_p_5, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.StatefulPartitionedCall_landmark_conv_37 = relu(dlarray(Vars.StatefulPartitionedCall_landmark_conv_34));
NumDims.StatefulPartitionedCall_landmark_conv_37 = NumDims.StatefulPartitionedCall_landmark_conv_34;

% BatchNormalization:
[offset, scale, datasetMean, datasetVariance, dataFormat, NumDims.StatefulPartitionedCall_landmark_batc_33, NumDims.StatefulPartitionedCall_landmark_batc_31, NumDims.StatefulPartitionedCall_landmark_batc_32] = prepareBatchNormalizationArgs(Vars.StatefulPartitionedCall_landmark_batc_35, Vars.StatefulPartitionedCall_landmark_batc_34, Vars.StatefulPartitionedCall_landmark_batc_31, Vars.StatefulPartitionedCall_landmark_batc_32, NumDims.StatefulPartitionedCall_landmark_conv_37, NumDims.StatefulPartitionedCall_landmark_batc_31, NumDims.StatefulPartitionedCall_landmark_batc_32);
if Training
    [Vars.StatefulPartitionedCall_landmark_batc_33, dsmean, dsvar] = batchnorm(Vars.StatefulPartitionedCall_landmark_conv_37, offset, scale, datasetMean, datasetVariance, 'Epsilon', 0.001000, 'DataFormat', dataFormat);
    Vars.StatefulPartitionedCall_landmark_batc_31 = dlarray(dsmean);
    Vars.StatefulPartitionedCall_landmark_batc_32 = dlarray(dsvar);
else
    Vars.StatefulPartitionedCall_landmark_batc_33 = batchnorm(Vars.StatefulPartitionedCall_landmark_conv_37, offset, scale, datasetMean, datasetVariance, 'Epsilon', 0.001000, 'DataFormat', dataFormat);
end

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.StatefulPartitionedCall_landmark_conv_40] = prepareConvArgs(Vars.StatefulPartitionedCall_landmark_conv_41, Vars.StatefulPartitionedCall_landmark_conv_39, Vars.ConvStride1029, Vars.ConvDilationFactor1030,Vars.ConvPadding1031, 1, NumDims.StatefulPartitionedCall_landmark_batc_33, NumDims.StatefulPartitionedCall_landmark_conv_41);
Vars.StatefulPartitionedCall_landmark_conv_40 = dlconv(Vars.StatefulPartitionedCall_landmark_batc_33, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.StatefulPartitionedCall_landmark_conv_43 = relu(dlarray(Vars.StatefulPartitionedCall_landmark_conv_40));
NumDims.StatefulPartitionedCall_landmark_conv_43 = NumDims.StatefulPartitionedCall_landmark_conv_40;

% BatchNormalization:
[offset, scale, datasetMean, datasetVariance, dataFormat, NumDims.StatefulPartitionedCall_landmark_batc_39, NumDims.StatefulPartitionedCall_landmark_batc_37, NumDims.StatefulPartitionedCall_landmark_batc_38] = prepareBatchNormalizationArgs(Vars.StatefulPartitionedCall_landmark_batc_41, Vars.StatefulPartitionedCall_landmark_batc_40, Vars.StatefulPartitionedCall_landmark_batc_37, Vars.StatefulPartitionedCall_landmark_batc_38, NumDims.StatefulPartitionedCall_landmark_conv_43, NumDims.StatefulPartitionedCall_landmark_batc_37, NumDims.StatefulPartitionedCall_landmark_batc_38);
if Training
    [Vars.StatefulPartitionedCall_landmark_batc_39, dsmean, dsvar] = batchnorm(Vars.StatefulPartitionedCall_landmark_conv_43, offset, scale, datasetMean, datasetVariance, 'Epsilon', 0.001000, 'DataFormat', dataFormat);
    Vars.StatefulPartitionedCall_landmark_batc_37 = dlarray(dsmean);
    Vars.StatefulPartitionedCall_landmark_batc_38 = dlarray(dsvar);
else
    Vars.StatefulPartitionedCall_landmark_batc_39 = batchnorm(Vars.StatefulPartitionedCall_landmark_conv_43, offset, scale, datasetMean, datasetVariance, 'Epsilon', 0.001000, 'DataFormat', dataFormat);
end

% MaxPool:
[poolsize, stride, padding, dataFormat, NumDims.StatefulPartitionedCall_landmark_max_p_7] = prepareMaxPool8Args(Vars.MaxPoolPoolSize1032, Vars.MaxPoolStride1033, Vars.MaxPoolPadding1034, NumDims.StatefulPartitionedCall_landmark_batc_39);
Vars.StatefulPartitionedCall_landmark_max_p_7 = maxpool(Vars.StatefulPartitionedCall_landmark_batc_39, poolsize, 'Stride', stride, 'Padding', padding, 'DataFormat', dataFormat);

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.StatefulPartitionedCall_landmark_conv_46] = prepareConvArgs(Vars.StatefulPartitionedCall_landmark_conv_47, Vars.StatefulPartitionedCall_landmark_conv_45, Vars.ConvStride1035, Vars.ConvDilationFactor1036,Vars.ConvPadding1037, 1, NumDims.StatefulPartitionedCall_landmark_max_p_7, NumDims.StatefulPartitionedCall_landmark_conv_47);
Vars.StatefulPartitionedCall_landmark_conv_46 = dlconv(Vars.StatefulPartitionedCall_landmark_max_p_7, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.StatefulPartitionedCall_landmark_conv_49 = relu(dlarray(Vars.StatefulPartitionedCall_landmark_conv_46));
NumDims.StatefulPartitionedCall_landmark_conv_49 = NumDims.StatefulPartitionedCall_landmark_conv_46;

% BatchNormalization:
[offset, scale, datasetMean, datasetVariance, dataFormat, NumDims.StatefulPartitionedCall_landmark_batc_45, NumDims.StatefulPartitionedCall_landmark_batc_43, NumDims.StatefulPartitionedCall_landmark_batc_44] = prepareBatchNormalizationArgs(Vars.StatefulPartitionedCall_landmark_batc_49, Vars.StatefulPartitionedCall_landmark_batc_48, Vars.StatefulPartitionedCall_landmark_batc_43, Vars.StatefulPartitionedCall_landmark_batc_44, NumDims.StatefulPartitionedCall_landmark_conv_49, NumDims.StatefulPartitionedCall_landmark_batc_43, NumDims.StatefulPartitionedCall_landmark_batc_44);
if Training
    [Vars.StatefulPartitionedCall_landmark_batc_45, dsmean, dsvar] = batchnorm(Vars.StatefulPartitionedCall_landmark_conv_49, offset, scale, datasetMean, datasetVariance, 'Epsilon', 0.001000, 'DataFormat', dataFormat);
    Vars.StatefulPartitionedCall_landmark_batc_43 = dlarray(dsmean);
    Vars.StatefulPartitionedCall_landmark_batc_44 = dlarray(dsvar);
else
    Vars.StatefulPartitionedCall_landmark_batc_45 = batchnorm(Vars.StatefulPartitionedCall_landmark_conv_49, offset, scale, datasetMean, datasetVariance, 'Epsilon', 0.001000, 'DataFormat', dataFormat);
end

% Transpose:
[perm, NumDims.StatefulPartitionedCall_landmark_batc_47] = prepareTransposeArgs(Vars.TransposePerm1038, NumDims.StatefulPartitionedCall_landmark_batc_45);
if isempty(perm)
    Vars.StatefulPartitionedCall_landmark_batc_47 = Vars.StatefulPartitionedCall_landmark_batc_45;
else
    Vars.StatefulPartitionedCall_landmark_batc_47 = permute(Vars.StatefulPartitionedCall_landmark_batc_45, perm);
end

% Reshape:
[shape, NumDims.StatefulPartitionedCall_landmark_flatt_1] = prepareReshapeArgs(Vars.StatefulPartitionedCall_landmark_batc_47, Vars.const_fold_opt__87, NumDims.StatefulPartitionedCall_landmark_batc_47, 0);
Vars.StatefulPartitionedCall_landmark_flatt_1 = reshape(Vars.StatefulPartitionedCall_landmark_batc_47, shape{:});

% MatMul:
[Vars.StatefulPartitionedCall_landmark_dense_9, NumDims.StatefulPartitionedCall_landmark_dense_9] = onnxMatMul(Vars.StatefulPartitionedCall_landmark_flatt_1, Vars.StatefulPartitionedCall_landmark_dense_8, NumDims.StatefulPartitionedCall_landmark_flatt_1, NumDims.StatefulPartitionedCall_landmark_dense_8);

% Add:
Vars.StatefulPartitionedCall_landmark_dense_7 = Vars.StatefulPartitionedCall_landmark_dense_9 + Vars.StatefulPartitionedCall_landmark_dense_6;
NumDims.StatefulPartitionedCall_landmark_dense_7 = max(NumDims.StatefulPartitionedCall_landmark_dense_9, NumDims.StatefulPartitionedCall_landmark_dense_6);

% Relu:
Vars.StatefulPartitionedCall_landmark_dens_10 = relu(dlarray(Vars.StatefulPartitionedCall_landmark_dense_7));
NumDims.StatefulPartitionedCall_landmark_dens_10 = NumDims.StatefulPartitionedCall_landmark_dense_7;

% Mul:
Vars.StatefulPartitionedCall_landmark_batc_54 = Vars.StatefulPartitionedCall_landmark_dens_10 .* Vars.StatefulPartitionedCall_landmark_batc_52;
NumDims.StatefulPartitionedCall_landmark_batc_54 = max(NumDims.StatefulPartitionedCall_landmark_dens_10, NumDims.StatefulPartitionedCall_landmark_batc_52);

% Add:
Vars.StatefulPartitionedCall_landmark_batc_51 = Vars.StatefulPartitionedCall_landmark_batc_54 + Vars.StatefulPartitionedCall_landmark_batc_55;
NumDims.StatefulPartitionedCall_landmark_batc_51 = max(NumDims.StatefulPartitionedCall_landmark_batc_54, NumDims.StatefulPartitionedCall_landmark_batc_55);

% MatMul:
[Vars.StatefulPartitionedCall_landmark_dense_5, NumDims.StatefulPartitionedCall_landmark_dense_5] = onnxMatMul(Vars.StatefulPartitionedCall_landmark_batc_51, Vars.StatefulPartitionedCall_landmark_dense_4, NumDims.StatefulPartitionedCall_landmark_batc_51, NumDims.StatefulPartitionedCall_landmark_dense_4);

% Add:
Vars.dense_1 = Vars.StatefulPartitionedCall_landmark_dense_5 + Vars.StatefulPartitionedCall_landmark_dense_2;
NumDims.dense_1 = max(NumDims.StatefulPartitionedCall_landmark_dense_5, NumDims.StatefulPartitionedCall_landmark_dense_2);

% Set graph output arguments from Vars and NumDims:
dense_1 = Vars.dense_1;
dense_1NumDims1040 = NumDims.dense_1;
% Set output state from Vars:
state = updateStruct(state, Vars);
end

function [inputDataPerms, outputDataPerms, Training] = parseInputs(image_input, numDataOutputs, params, varargin)
% Function to validate inputs to landmarkFcn:
p = inputParser;
isValidArrayInput = @(x)isnumeric(x) || isstring(x);
isValidONNXParameters = @(x)isa(x, 'ONNXParameters');
addRequired(p, 'image_input', isValidArrayInput);
addRequired(p, 'params', isValidONNXParameters);
addParameter(p, 'InputDataPermutation', 'auto');
addParameter(p, 'OutputDataPermutation', 'auto');
addParameter(p, 'Training', false);
parse(p, image_input, params, varargin{:});
inputDataPerms = p.Results.InputDataPermutation;
outputDataPerms = p.Results.OutputDataPermutation;
Training = p.Results.Training;
if isnumeric(inputDataPerms)
    inputDataPerms = {inputDataPerms};
end
if isstring(inputDataPerms) && isscalar(inputDataPerms) || ischar(inputDataPerms)
    inputDataPerms = repmat({inputDataPerms},1,1);
end
if isnumeric(outputDataPerms)
    outputDataPerms = {outputDataPerms};
end
if isstring(outputDataPerms) && isscalar(outputDataPerms) || ischar(outputDataPerms)
    outputDataPerms = repmat({outputDataPerms},1,numDataOutputs);
end
end

function [image_input, Training, outputDataPerms, anyDlarrayInputs] = preprocessInput(image_input, params, varargin)
% Parse input arguments
[inputDataPerms, outputDataPerms, Training] = parseInputs(image_input, 1, params, varargin{:});
anyDlarrayInputs = any(cellfun(@(x)isa(x, 'dlarray'), {image_input}));
% Make the input variables into unlabelled dlarrays:
image_input = makeUnlabeledDlarray(image_input);
% Permute inputs if requested:
image_input = permuteInputVar(image_input, inputDataPerms{1}, 4);
% Check input size(s):
checkInputSize(size(image_input), {'unk__88' 128 128 3}, "image_input");
end

function [dense_1] = postprocessOutput(dense_1, outputDataPerms, anyDlarrayInputs, Training, varargin)
% Set output type:
if ~anyDlarrayInputs && ~Training
    if isdlarray(dense_1)
        dense_1 = extractdata(dense_1);
    end
end
% Permute outputs if requested:
dense_1 = permuteOutputVar(dense_1, outputDataPerms{1}, 2);
end


%% dlarray functions implementing ONNX operators:

function [D, numDimsD] = onnxMatMul(A, B, numDimsA, numDimsB)
% Implements the ONNX MatMul operator.

% Copyright 2020-2023 The MathWorks, Inc.

% If B is 1-D, temporarily extend it to a row vector
if numDimsB==1
    B = B(:)';
end
maxNumDims = max(numDimsA, numDimsB);
numDimsD = maxNumDims;
if maxNumDims > 2
    % Removes dlarray formats if only one of the input dlarrays is formatted.
    if sum([isempty(dims(A)), isempty(dims(B))]) == 1
        D = pagemtimes(stripdims(B), stripdims(A));
    else
        %computes matrix product of corresponding pages of input arrays A and
        %B.
        D = pagemtimes(B, A);
    end
else
    D = B * A;
    if numDimsA==1 || numDimsB==1
        D = D(:);
        numDimsD = 1;
    end
end
end

function [offset, scale, datasetMean, datasetVariance, dataFormat, numDimsY, numDimsDatasetMean, numDimsDatasetVariance] = prepareBatchNormalizationArgs(...
    offset, scale, datasetMean, datasetVariance, numDimsX, numDimsDatasetMean, numDimsDatasetVariance)
% Prepares arguments for implementing the ONNX BatchNormalization operator

%   Copyright 2020-2024 The MathWorks, Inc.

offset = dlarray(offset,'C');
scale = dlarray(scale,'C');
if isdlarray(datasetMean)
    datasetMean = extractdata(datasetMean);
end
if isdlarray(datasetVariance)
    datasetVariance = extractdata(datasetVariance);
end
datasetVariance(datasetVariance <= 0) = realmin('single');  % Set nonpositive variance components to a value below eps('single')
dataFormat = [repmat('S', 1, numDimsX-2), 'CB'];
numDimsY = numDimsX;
end

function [weights, bias, stride, dilationFactor, padding, dataFormat, numDimsY] = prepareConvArgs(...
    weights, bias, stride, dilationFactor, padding, numWtGroups, numDimsX, numDimsW)
% Prepares arguments for implementing the ONNX Conv operator

%   Copyright 2020 The MathWorks, Inc.

% Weights: The ONNX weight dim is Fcxyz..., where c=C/G, G is numGroups,
% and xyz... are spatial dimensions. DLT "weights" here is the flip of
% that, or ...zyxcF. dlconv requires ...zyxcfG, where f=F/G. So reshape to
% split the last dimension.
sizeW    = size(weights, 1:numDimsW);
F        = sizeW(end);
newWSize = [sizeW(1:numDimsW-1), F/numWtGroups, numWtGroups];
weights  = reshape(weights, newWSize);
% bias
if isempty(bias)
    bias = 0;
end
bias = dlarray(bias(:),'CU');
% Derive missing default attributes from weight tensor
numSpatialDims = numDimsW-2;
if isempty(padding)
    padding = zeros(1, 2*numSpatialDims);
end
if isempty(stride)
    stride = ones(1,numSpatialDims);
end
if isempty(dilationFactor)
    dilationFactor = ones(1,numSpatialDims);
end
% Make the attributes non-dlarrays:
if isa(stride, 'dlarray')
    stride = extractdata(stride);
end
if isa(dilationFactor, 'dlarray')
    dilationFactor = extractdata(dilationFactor);
end
if isa(padding, 'dlarray')
    padding = extractdata(padding);
end
% Make the attributes double row vectors, and flip their dimension ordering
% to reverse-onnx:
stride = fliplr(double(stride(:)'));
dilationFactor = fliplr(double(dilationFactor(:)'));
if isnumeric(padding)       % padding can be "same"
    % ONNX: [x1_begin, ..., xn_begin, x1_end, ...,xn_end]
    % DLT:  [xn_begin, ..., x1_begin;
    %        xn_end, ..., x1_end]       (Note the lrflip and semicolon)
    padding = fliplr(transpose(reshape(padding, [], 2)));
end
% Set dataformat and numdims
dataFormat = [repmat('S', 1, numDimsX-2) 'CB'];
numDimsY = numDimsX;
end

function [poolsize, stride, padding, dataFormat, numDimsY, numDimsIndices] = prepareMaxPool8Args(poolsize, stride, padding, numDimsX)
% Prepares arguments for implementing the ONNX MaxPool-8 operator

%   Copyright 2020 The MathWorks, Inc.

poolsize    = fliplr(extractdata(poolsize(:)'));
stride      = fliplr(extractdata(stride(:)'));
% padding
if isa(padding, 'dlarray')
    padding = extractdata(padding);
end
if isnumeric(padding)
    % ONNX: [x1_begin, ..., xn_begin, x1_end, ...,xn_end]
    % DLT:  [xn_begin, ..., x1_begin;
    %        xn_end, ..., x1_end]       (Note the lrflip and semicolon)
    padding = fliplr(transpose(reshape(padding, [], 2)));
end
dataFormat  = [repmat('S', 1, numDimsX-2) 'CB'];
numDimsY    = numDimsX;
numDimsIndices = numDimsX;                      % New in opset 8
end

function [DLTShape, numDimsY] = prepareReshapeArgs(X, ONNXShape, numDimsX, allowzero)
% Prepares arguments for implementing the ONNX Reshape operator

%   Copyright 2020-2024 The MathWorks, Inc.

ONNXShape = flip(extractdata(ONNXShape));            % First flip the shape to make it correspond to the dimensions of X.
% In ONNX, 0 means "unchanged" if allowzero is false, and -1 means "infer". In DLT, there is no
% "unchanged", and [] means "infer".
DLTShape = num2cell(ONNXShape);                      % Make a cell array so we can include [].
% Replace zeros with the actual size if allowzero is false
if any(ONNXShape==0) && allowzero==0
    i0 = find(ONNXShape==0);
    DLTShape(i0) = num2cell(size(X, numDimsX - numel(ONNXShape) + i0));  % right-align the shape vector and dims
end
if any(ONNXShape == -1)
    % Replace -1 with []
    i = ONNXShape == -1;
    DLTShape{i} = [];
end
if numel(DLTShape)==1
    DLTShape = [DLTShape 1];
end
numDimsY = numel(ONNXShape);
end

function [perm, numDimsA] = prepareTransposeArgs(ONNXPerm, numDimsA)
% Prepares arguments for implementing the ONNX Transpose operator

%   Copyright 2020 The MathWorks, Inc.

if numDimsA <= 1        % Tensors of numDims 0 or 1 are unchanged by ONNX Transpose.
    perm = [];
else
    if isempty(ONNXPerm)        % Empty ONNXPerm means reverse the dimensions.
        perm = numDimsA:-1:1;
    else
        perm = numDimsA-flip(ONNXPerm);
    end
end
end

%% Utility functions:

function s = appendStructs(varargin)
% s = appendStructs(s1, s2,...). Assign all fields in s1, s2,... into s.

%   Copyright 2020 The MathWorks, Inc.

if isempty(varargin)
    s = struct;
else
    s = varargin{1};
    for i = 2:numel(varargin)
        fromstr = varargin{i};
        fs = fieldnames(fromstr);
        for j = 1:numel(fs)
            s.(fs{j}) = fromstr.(fs{j});
        end
    end
end
end

function checkInputSize(inputShape, expectedShape, inputName)

%   Copyright 2020-2021 The MathWorks, Inc.

if numel(expectedShape)==0
    % The input is a scalar
    if ~isequal(inputShape, [1 1])
        inputSizeStr = makeSizeString(inputShape);
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, "[1,1]", inputSizeStr));
    end
elseif numel(expectedShape)==1
    % The input is a vector
    if ~shapeIsColumnVector(inputShape) || ~iSizesMatch({inputShape(1)}, expectedShape)
        expectedShape{2} = 1;
        expectedSizeStr = makeSizeString(expectedShape);
        inputSizeStr = makeSizeString(inputShape);
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, expectedSizeStr, inputSizeStr));
    end
else
    % The input has 2 dimensions or more

    % The input dimensions have been reversed; flip them back to compare to the
    % expected ONNX shape.
    inputShape = fliplr(inputShape);

    % If the expected shape has fewer dims than the input shape, error.
    if numel(expectedShape) < numel(inputShape)
        expectedSizeStr = strjoin(["[", strjoin(string(expectedShape), ","), "]"], "");
        error(message('nnet_cnn_onnx:onnx:InputHasGreaterNDims', inputName, expectedSizeStr));
    end

    % Prepad the input shape with trailing ones up to the number of elements in
    % expectedShape
    inputShape = num2cell([ones(1, numel(expectedShape) - length(inputShape)) inputShape]);

    % Find the number of variable size dimensions in the expected shape
    numVariableInputs = sum(cellfun(@(x) isa(x, 'char') || isa(x, 'string'), expectedShape));

    % Find the number of input dimensions that are not in the expected shape
    % and cannot be represented by a variable dimension
    nonMatchingInputDims = setdiff(string(inputShape), string(expectedShape));
    numNonMatchingInputDims  = numel(nonMatchingInputDims) - numVariableInputs;

    expectedSizeStr = makeSizeString(expectedShape);
    inputSizeStr = makeSizeString(inputShape);
    if numNonMatchingInputDims == 0 && ~iSizesMatch(inputShape, expectedShape)
        % The actual and expected input dimensions match, but in
        % a different order. The input needs to be permuted.
        error(message('nnet_cnn_onnx:onnx:InputNeedsPermute',inputName, expectedSizeStr, inputSizeStr));
    elseif numNonMatchingInputDims > 0
        % The actual and expected input sizes do not match.
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, expectedSizeStr, inputSizeStr));
    end
end
end

function doesMatch = iSizesMatch(inputShape, expectedShape)
% Check whether the input and expected shapes match, in order.
% Size elements match if (1) the elements are equal, or (2) the expected
% size element is a variable (represented by a character vector or string)
doesMatch = true;
for i=1:numel(inputShape)
    if ~(isequal(inputShape{i},expectedShape{i}) || ischar(expectedShape{i}) || isstring(expectedShape{i}))
        doesMatch = false;
        return
    end
end
end

function sizeStr = makeSizeString(shape)
sizeStr = strjoin(["[", strjoin(string(shape), ","), "]"], "");
end

function isVec = shapeIsColumnVector(shape)
if numel(shape) == 2 && shape(2) == 1
    isVec = true;
else
    isVec = false;
end
end
function X = makeUnlabeledDlarray(X)
% Make numeric X into an unlabelled dlarray

%   Copyright 2020-2021 The MathWorks, Inc.

if isa(X, 'dlarray')
    X = stripdims(X);
elseif isnumeric(X)
    if isinteger(X)
        % Make ints double so they can combine with anything without
        % reducing precision
        X = double(X);
    end
    X = dlarray(X);
end
end

function [Vars, NumDims] = packageVariables(params, inputNames, inputValues, inputNumDims)

%   Copyright 2020 The MathWorks, Inc.

% inputNames, inputValues are cell arrays. inputRanks is a numeric vector.
Vars = appendStructs(params.Learnables, params.Nonlearnables, params.State);
NumDims = params.NumDimensions;
% Add graph inputs
for i = 1:numel(inputNames)
    Vars.(inputNames{i}) = inputValues{i};
    NumDims.(inputNames{i}) = inputNumDims(i);
end
end

function X = permuteInputVar(X, userDataPerm, onnxNDims)

%   Copyright 2020-2021 The MathWorks, Inc.
% Returns reverse-ONNX ordering
if onnxNDims == 0
    return;
elseif onnxNDims == 1 && isvector(X)
    X = X(:);
    return;
elseif isnumeric(userDataPerm)
    % Permute into reverse ONNX ordering
    if numel(userDataPerm) ~= onnxNDims
        error(message('nnet_cnn_onnx:onnx:InputPermutationSize', numel(userDataPerm), onnxNDims));
    end
    perm = fliplr(userDataPerm);
elseif isequal(userDataPerm, 'auto') && onnxNDims == 4
    % Permute MATLAB HWCN to reverse onnx (WHCN)
    perm = [2 1 3 4];
elseif isequal(userDataPerm, 'as-is')
    % Do not permute the input
    perm = 1:ndims(X);
else
    % userDataPerm is either 'none' or 'auto' with no default, which means
    % it's already in onnx ordering, so just make it reverse onnx
    perm = max(2,onnxNDims):-1:1;
end
X = permute(X, perm);
end

function Y = permuteOutputVar(Y, userDataPerm, onnxNDims)

%   Copyright 2020-2021 The MathWorks, Inc.
switch onnxNDims
    case 0
        perm = [];
    case 1
        if isnumeric(userDataPerm)
            % Use the user's permutation because Y is a column vector which
            % already matches ONNX.
            perm = userDataPerm;
        elseif isequal(userDataPerm, 'auto')
            % Treat the 1D onnx vector as a 2D column and transpose it
            perm = [2 1];
        else
            % userDataPerm is 'none'. Leave Y alone because it already
            % matches onnx.
            perm = [];
        end
    otherwise
        % ndims >= 2
        if isnumeric(userDataPerm)
            % Use the inverse of the user's permutation. This is not just the
            % flip of the permutation vector.
            perm = onnxNDims + 1 - userDataPerm;
        elseif isequal(userDataPerm, 'auto')
            if onnxNDims == 2
                % Permute reverse ONNX CN to DLT CN (do nothing)
                perm = [];
            elseif onnxNDims == 4
                % Permute reverse onnx (WHCN) to MATLAB HWCN
                perm = [2 1 3 4];
            else
                % User wants the output in ONNX ordering, so just reverse it from
                % reverse onnx
                perm = onnxNDims:-1:1;
            end
        elseif isequal(userDataPerm, 'as-is')
            % Do not permute the input
            perm = 1:ndims(Y);
        else
            % userDataPerm is 'none', so just make it reverse onnx
            perm = onnxNDims:-1:1;
        end
end
if ~isempty(perm)
    Y = permute(Y, perm);
end
end

function s = updateStruct(s, t)
% Set all existing fields in s from fields in t, ignoring extra fields in
% t.
%   Copyright 2020 The MathWorks, Inc.

for name = transpose(fieldnames(s))
    s.(name{1}) = t.(name{1});
end
end
